version: '3.8'

services:
  wwh_postgres:
    image: postgis/postgis
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_volume: